
version: '3'

networks:

    local-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16

services:

    mysql-server:
        restart: always
        build: mysql
        networks:
            local-net:
                ipv4_address: 172.18.0.2
        volumes:
            - /docker/mysql/crontab:/docker/crontab:ro
            - /docker/mysql/entrypoint.sh:/docker/entrypoint.sh:ro
            - /docker/mysql/mysql-backup.sh:/docker/mysql-backup.sh:ro
            - /docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
            - /storage/mysql:/var/lib/mysql
            - /storage/mysql-backup:/mysql-backup
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=pwd159357
        command: /bin/bash /docker/entrypoint.sh

    redis-server:
        restart: always
        build: redis
        networks:
            local-net:
                ipv4_address: 172.18.0.3
        volumes:
            - /docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro

    hagworm-service:
        restart: always
        build: python
        networks:
            local-net:
                ipv4_address: 172.18.0.4
        volumes:
            - /docker/python/entrypoint.sh:/docker/entrypoint.sh:ro
            - /storage/source:/source:ro
        command: /bin/bash /docker/entrypoint.sh

    proxy-server:
        restart: always
        build: nginx
        ports:
            - "80:80"
        networks:
            local-net:
                ipv4_address: 172.18.0.5
        volumes:
            - /docker/nginx/crontab:/docker/crontab:ro
            - /docker/nginx/entrypoint.sh:/docker/entrypoint.sh:ro
            - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /docker/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
            - /storage/source:/source:ro
            - /storage/static:/static:ro
            - /storage/nginx-log:/nginx-log
        command: /bin/bash /docker/entrypoint.sh
